In [106]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from collections import Counter

In [111]:
iris = datasets.load_iris() 
X = iris.data
y = iris.target
names = iris.target_names

In [127]:
print(X[:5])
print(y[:5])
print(names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']


In [128]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [114]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))
#print(x_test[:10])

120
30
120
30


In [115]:
def euclidean(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=(ix-ix2)**2
    return np.sqrt(sum)

In [116]:
#euclidean([0,0], [3,4])

In [117]:
xt=[5.1, 3., 4.2, 1.5]

In [118]:
dist={}
for i, x in enumerate(x_train):
    ed=euclidean(x, xt)
    dist[i]=ed


In [119]:
#print(dist)

In [120]:
sorted_d = sorted(dist.items(), key=lambda kv: kv[1])

In [121]:
print(sorted_d)

[(108, 0.4242640687119289), (34, 0.44721359549995815), (72, 0.5477225575051662), (57, 0.58309518948453), (47, 0.6403124237432853), (91, 0.6480740698407857), (7, 0.6708203932499371), (60, 0.6708203932499374), (70, 0.6708203932499376), (11, 0.7000000000000002), (114, 0.7280109889280523), (79, 0.8000000000000007), (75, 0.8660254037844387), (55, 0.871779788708135), (53, 0.9165151389911683), (81, 0.9539392014169459), (24, 1.009950493836208), (54, 1.0148891565092222), (42, 1.0344080432788603), (16, 1.0583005244258363), (27, 1.0630145812734653), (8, 1.0816653826391966), (48, 1.1224972160321824), (43, 1.1224972160321829), (13, 1.1269427669584644), (15, 1.126942766958465), (61, 1.174734012447073), (113, 1.2083045973594573), (4, 1.2247448713915892), (49, 1.2409673645990857), (65, 1.244989959798873), (107, 1.244989959798873), (5, 1.24899959967968), (14, 1.2569805089976536), (88, 1.30384048104053), (56, 1.319090595827292), (112, 1.3228756555322954), (119, 1.322875655532296), (62, 1.337908816025965

In [129]:
k=119
neighbors=[]
for i in range(k):
    neighbors.append(sorted_d[i][0])
print(neighbors)

[108, 34, 72, 57, 47, 91, 7, 60, 70, 11, 114, 79, 75, 55, 53, 81, 24, 54, 42, 16, 27, 8, 48, 43, 13, 15, 61, 113, 4, 49, 65, 107, 5, 14, 88, 56, 112, 119, 62, 98, 68, 103, 97, 37, 78, 10, 82, 3, 29, 116, 36, 85, 95, 12, 67, 40, 89, 86, 66, 30, 35, 44, 17, 52, 93, 45, 26, 22, 90, 83, 41, 31, 76, 58, 19, 38, 33, 6, 59, 99, 100, 106, 69, 101, 111, 102, 74, 28, 94, 46, 118, 51, 18, 32, 84, 50, 110, 92, 1, 117, 25, 115, 104, 105, 77, 39, 9, 109, 20, 80, 2, 73, 63, 23, 96, 0, 71, 64, 87]


In [130]:
classes=[ y_train[i] for i in neighbors]
print(classes)

[2, 1, 2, 0, 1, 0, 2, 2, 1, 2, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 1, 2, 0, 1, 0, 1, 2, 2, 1, 2, 2, 0, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 2, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 1, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 0, 1, 2, 0, 0, 2, 0, 0, 2, 1, 2, 0, 0, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0]


In [131]:
count=Counter(classes)
print(count)

Counter({0: 41, 2: 40, 1: 38})


In [125]:
keys= list( count.keys() )
print('keys=', keys)
values=list( count.values() )
print('values=',values)

keys= [1, 2, 0]
values= [42, 39, 34]


In [126]:
index_of_max_values=values.index(max(values)) 
print('index of max value=', index_of_max_values)
y_hat=keys[index_of_max_values]
print('predict class=',y_hat)

index of max value= 0
predict class= 1
