In [69]:
import numpy as np
import matplotlib.pyplot as plt 
import pprint 
from sklearn import datasets
from sklearn.metrics import accuracy_score

In [70]:
iris =  datasets.load_iris() 
x = iris.data[:]  #all columns
y = iris.target[:]
#names = iris.target_names

In [71]:
#print(x)
#print(y)
#print(names)

In [72]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [73]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def linRG(x, theta):
    return np.dot(theta, x.T)

def predict(x, theta):
    z = linRG(x, theta)
    return sigmoid(z)

def loss(h, y):
    return (- y * np.log(h) - (1 - y ) * np.log(1 - h) ).mean()

def gradient(x, h, y):
    n = x.shape[0]
    return (1 / n) * np.dot( (h - y), x)
    
def train(x,y, epoch, lr, theta):
    for i in range(epoch):
        h=predict(x, theta)  
        gd=gradient(x, h, y)
        theta = theta-lr * gd 
    return theta

In [74]:
ix=x[:]
#print(ix.shape)
ix2=np.ones((ix.shape[0],  1))
ix2=np.append(ix2, ix , axis=1)
x=ix2
print(x[:5])

[[1.  5.1 3.5 1.4 0.2]
 [1.  4.9 3.  1.4 0.2]
 [1.  4.7 3.2 1.3 0.2]
 [1.  4.6 3.1 1.5 0.2]
 [1.  5.  3.6 1.4 0.2]]


In [81]:
k=150         #classes
#print(y)

In [82]:
#thetas=np.zeros( (k, x[0].shape[0]) )
#print(thetas)

In [84]:
epoch=9000
lr=0.1

thetas=np.zeros( (k, x[0].shape[0]) )

for ik in range(k):
    tmp_y = np.array(y==ik, dtype = int)
    theta = np.zeros(x[0].shape[0])
    theta = train(x,tmp_y, epoch, lr, theta)
    thetas[ik]=theta
    
print(thetas)

[[ 0.49929245  0.78736613  2.75039624 -4.28206578 -1.96950436]
 [ 4.77352113  0.09813051 -2.44837642  1.18573166 -2.73197721]
 [-4.04052273 -3.76151078 -3.90282494  5.60851497  6.72936562]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15499255]
 [-0.23259356 -1.22153515 -0.72676535 -0.57657794 -0.15

In [78]:
pd=predict(x,thetas)
print(pd.shape)

(150, 150)


In [79]:
prd=[]
for i in range(pd.shape[1]):
    
    vals= [pd[0][i], pd[1][i], pd[2][i]]
    m=np.argmax(vals)
    prd.append(m)
    
print(prd)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [86]:
print(accuracy_score(y, prd) * 100)

96.66666666666667
