# Topic: Naive Bayes Classifier

Md Kamran Ahmad

ID:160103020033

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pprint 
from sklearn import datasets
from sklearn.metrics import accuracy_score

In [2]:
iris =  datasets.load_iris() 
x = iris.data 
y = iris.target
#names = iris.target_names

In [3]:
print(x[:3])
#print(y)
#print(names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [4]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [5]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def linRG(x, theta):
    return np.dot(theta, x.T)

def predict(x, theta):
    z = linRG(x, theta)
    return sigmoid(z)

def loss(h, y):
    return (- y * np.log(h) - (1 - y ) * np.log(1 - h) ).mean()

def gradient(x, h, y):
    n = x.shape[0]
    return (1 / n) * np.dot( (h - y), x)
    
def train(x,y, epoch, lr, theta):
    for i in range(epoch):
        h=predict(x, theta)  
        gd=gradient(x, h, y)
        theta = theta-lr * gd 
    return theta

In [6]:
ix=x[:]
#print(ix.shape)
ix2=np.ones((ix.shape[0],  1))
#print(ix2)
ix2=np.append(ix2, ix , axis=1)
x=ix2
print(x[:5])

[[1.  5.1 3.5 1.4 0.2]
 [1.  4.9 3.  1.4 0.2]
 [1.  4.7 3.2 1.3 0.2]
 [1.  4.6 3.1 1.5 0.2]
 [1.  5.  3.6 1.4 0.2]]


In [7]:
k=7         #classes

In [8]:
#thetas=np.zeros( (k, x[0].shape[0]) )
#print(thetas)

In [9]:
epoch=90000
lr=0.0001
thetas=np.zeros( (k, x[0].shape[0]))
#print(thetas)
for i in range(k):
    tmp_y = np.array(y==i, dtype = int)
    theta = np.zeros(x[0].shape[0])
    theta = train(x,tmp_y, epoch, lr, theta)
    thetas[i]=theta
    
print(thetas)

[[ 0.16683979  0.25485315  0.87983751 -1.41108308 -0.63840969]
 [ 0.02119505 -0.03716548 -0.55488718  0.32380194 -0.10848256]
 [-0.28495127 -0.63864028 -0.70141415  1.04994391  0.74157251]
 [-0.12110195 -0.65854164 -0.37674295 -0.34803906 -0.10052107]
 [-0.12110195 -0.65854164 -0.37674295 -0.34803906 -0.10052107]
 [-0.12110195 -0.65854164 -0.37674295 -0.34803906 -0.10052107]
 [-0.12110195 -0.65854164 -0.37674295 -0.34803906 -0.10052107]]


In [10]:
#predict all data
pd=predict(x, thetas)
#print(pd)

In [11]:
prd=[]
print(pd.shape[1])
for i in range(pd.shape[1]):
    vals= [pd[0][i], pd[1][i], pd[2][i]]
    m=np.argmax(vals)
    prd.append(m)
    
print(prd)

150
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [12]:
mm=np.argmax(pd, axis=0)
print(mm)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 2 1 2 2 1 1 2 1 2 1 2 1 1 2 1 2 1 2 1 2 2
 1 1 1 2 2 1 1 1 1 2 2 2 1 1 1 2 2 2 1 1 2 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
print(accuracy_score(y, prd) * 100)

86.66666666666667


In [14]:
ar=[1, 1.9 , 3.0 , 2.4 , 3.2]
ar=np.array(ar)
print(ar)

[1.  1.9 3.  2.4 3.2]


In [15]:
npd=predict(ar, thetas[0])
npd1=predict(ar, thetas[1])
npd2=predict(ar, thetas[2])
print(npd, npd1, npd2)

npdr=[npd, npd1, npd2]
npv=np.argmax(npdr)
print(npv)

0.10536954032298042 0.21685304723918852 0.784195786731975
2
